/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface NFTMarketPlaceInterface extends Interface {
    getFunction(nameOrSignature: "admin" | "buyNFT" | "cancelOrder" | "createOrder" | "createOrderWithEscrow" | "nextOrderId" | "orders" | "platformFee"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "OrderCancelled" | "OrderCreated" | "OrderExecuted"): EventFragment;

    encodeFunctionData(functionFragment: 'admin', values?: undefined): string;
encodeFunctionData(functionFragment: 'buyNFT', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'cancelOrder', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'createOrder', values: [AddressLike, BigNumberish, BigNumberish, AddressLike, string]): string;
encodeFunctionData(functionFragment: 'createOrderWithEscrow', values: [AddressLike, BigNumberish, BigNumberish, AddressLike, string]): string;
encodeFunctionData(functionFragment: 'nextOrderId', values?: undefined): string;
encodeFunctionData(functionFragment: 'orders', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'platformFee', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'admin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'buyNFT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelOrder', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createOrder', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createOrderWithEscrow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextOrderId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'orders', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'platformFee', data: BytesLike): Result;
  }

  
    export namespace OrderCancelledEvent {
      export type InputTuple = [orderId: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [orderId: bigint, timestamp: bigint];
      export interface OutputObject {orderId: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OrderCreatedEvent {
      export type InputTuple = [orderId: BigNumberish, seller: AddressLike, nftContract: AddressLike, tokenId: BigNumberish, cid: string, price: BigNumberish, paymentToken: AddressLike, timestamp: BigNumberish, isActive: boolean, isEscrowed: boolean];
      export type OutputTuple = [orderId: bigint, seller: string, nftContract: string, tokenId: bigint, cid: string, price: bigint, paymentToken: string, timestamp: bigint, isActive: boolean, isEscrowed: boolean];
      export interface OutputObject {orderId: bigint, seller: string, nftContract: string, tokenId: bigint, cid: string, price: bigint, paymentToken: string, timestamp: bigint, isActive: boolean, isEscrowed: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OrderExecutedEvent {
      export type InputTuple = [orderId: BigNumberish, buyer: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [orderId: bigint, buyer: string, timestamp: bigint];
      export interface OutputObject {orderId: bigint, buyer: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface NFTMarketPlace extends BaseContract {
    
    connect(runner?: ContractRunner | null): NFTMarketPlace;
    waitForDeployment(): Promise<this>;

    interface: NFTMarketPlaceInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    admin: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    buyNFT: TypedContractMethod<
      [_orderId: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    cancelOrder: TypedContractMethod<
      [_orderId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    createOrder: TypedContractMethod<
      [nftContract: AddressLike, tokenId: BigNumberish, price: BigNumberish, paymentToken: AddressLike, cid: string, ],
      [void],
      'nonpayable'
    >
    

    
    createOrderWithEscrow: TypedContractMethod<
      [nftContract: AddressLike, tokenId: BigNumberish, price: BigNumberish, paymentToken: AddressLike, cid: string, ],
      [void],
      'nonpayable'
    >
    

    
    nextOrderId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    orders: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, bigint, string, bigint, string, boolean, boolean] & {orderId: bigint, seller: string, nftContract: string, tokenId: bigint, cid: string, price: bigint, paymentToken: string, isActive: boolean, isEscrowed: boolean }],
      'view'
    >
    

    
    platformFee: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'admin'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'buyNFT'): TypedContractMethod<
      [_orderId: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'cancelOrder'): TypedContractMethod<
      [_orderId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createOrder'): TypedContractMethod<
      [nftContract: AddressLike, tokenId: BigNumberish, price: BigNumberish, paymentToken: AddressLike, cid: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createOrderWithEscrow'): TypedContractMethod<
      [nftContract: AddressLike, tokenId: BigNumberish, price: BigNumberish, paymentToken: AddressLike, cid: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'nextOrderId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'orders'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, bigint, string, bigint, string, boolean, boolean] & {orderId: bigint, seller: string, nftContract: string, tokenId: bigint, cid: string, price: bigint, paymentToken: string, isActive: boolean, isEscrowed: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'platformFee'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    getEvent(key: 'OrderCancelled'): TypedContractEvent<OrderCancelledEvent.InputTuple, OrderCancelledEvent.OutputTuple, OrderCancelledEvent.OutputObject>;
getEvent(key: 'OrderCreated'): TypedContractEvent<OrderCreatedEvent.InputTuple, OrderCreatedEvent.OutputTuple, OrderCreatedEvent.OutputObject>;
getEvent(key: 'OrderExecuted'): TypedContractEvent<OrderExecutedEvent.InputTuple, OrderExecutedEvent.OutputTuple, OrderExecutedEvent.OutputObject>;

    filters: {
      
      'OrderCancelled(uint256,uint256)': TypedContractEvent<OrderCancelledEvent.InputTuple, OrderCancelledEvent.OutputTuple, OrderCancelledEvent.OutputObject>;
      OrderCancelled: TypedContractEvent<OrderCancelledEvent.InputTuple, OrderCancelledEvent.OutputTuple, OrderCancelledEvent.OutputObject>;
    

      'OrderCreated(uint256,address,address,uint256,string,uint256,address,uint256,bool,bool)': TypedContractEvent<OrderCreatedEvent.InputTuple, OrderCreatedEvent.OutputTuple, OrderCreatedEvent.OutputObject>;
      OrderCreated: TypedContractEvent<OrderCreatedEvent.InputTuple, OrderCreatedEvent.OutputTuple, OrderCreatedEvent.OutputObject>;
    

      'OrderExecuted(uint256,address,uint256)': TypedContractEvent<OrderExecutedEvent.InputTuple, OrderExecutedEvent.OutputTuple, OrderExecutedEvent.OutputObject>;
      OrderExecuted: TypedContractEvent<OrderExecutedEvent.InputTuple, OrderExecutedEvent.OutputTuple, OrderExecutedEvent.OutputObject>;
    
    };
  }