/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as dexTokenSol from './DexToken.sol/index.ts';
export type { dexTokenSol };
import type * as interfacesSol from './Interfaces.sol/index.ts';
export type { interfacesSol };
import type * as uniswapV2PairSol from './UniswapV2Pair.sol/index.ts';
export type { uniswapV2PairSol };
export type { UniswapV2Factory } from './UniswapV2Factory.ts';
export type { UniswapV2Router } from './UniswapV2Router.ts';