/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../../common.ts"
  

  export interface UniswapV2RouterInterface extends Interface {
    getFunction(nameOrSignature: "addLiquidity" | "factory" | "getAmountsOut" | "removeLiquidity" | "swapExactTokensForTokens" | "x"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Increment" | "RemoveEvent"): EventFragment;

    encodeFunctionData(functionFragment: 'addLiquidity', values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BigNumberish, BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'factory', values?: undefined): string;
encodeFunctionData(functionFragment: 'getAmountsOut', values: [BigNumberish, AddressLike[]]): string;
encodeFunctionData(functionFragment: 'removeLiquidity', values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BigNumberish, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'swapExactTokensForTokens', values: [BigNumberish, BigNumberish, AddressLike[], AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'x', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'addLiquidity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'factory', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAmountsOut', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removeLiquidity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'swapExactTokensForTokens', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'x', data: BytesLike): Result;
  }

  
    export namespace IncrementEvent {
      export type InputTuple = [to: AddressLike, pair: AddressLike, token0: AddressLike, token1: AddressLike, token0Amount: BigNumberish, token1Amount: BigNumberish, token0AmountMin: BigNumberish, token1AmountMin: BigNumberish, amountA: BigNumberish, amountB: BigNumberish, liquidity: BigNumberish];
      export type OutputTuple = [to: string, pair: string, token0: string, token1: string, token0Amount: bigint, token1Amount: bigint, token0AmountMin: bigint, token1AmountMin: bigint, amountA: bigint, amountB: bigint, liquidity: bigint];
      export interface OutputObject {to: string, pair: string, token0: string, token1: string, token0Amount: bigint, token1Amount: bigint, token0AmountMin: bigint, token1AmountMin: bigint, amountA: bigint, amountB: bigint, liquidity: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RemoveEventEvent {
      export type InputTuple = [step: BigNumberish, pair: AddressLike, allowance: BigNumberish];
      export type OutputTuple = [step: bigint, pair: string, allowance: bigint];
      export interface OutputObject {step: bigint, pair: string, allowance: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface UniswapV2Router extends BaseContract {
    
    connect(runner?: ContractRunner | null): UniswapV2Router;
    waitForDeployment(): Promise<this>;

    interface: UniswapV2RouterInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addLiquidity: TypedContractMethod<
      [tokenA: AddressLike, tokenB: AddressLike, amountADesired: BigNumberish, amountBDesired: BigNumberish, amountAMin: BigNumberish, amountBMin: BigNumberish, to: AddressLike, ],
      [[bigint, bigint, bigint] & {amountA: bigint, amountB: bigint, liquidity: bigint }],
      'nonpayable'
    >
    

    
    factory: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getAmountsOut: TypedContractMethod<
      [amountIn: BigNumberish, path: AddressLike[], ],
      [bigint[]],
      'view'
    >
    

    
    removeLiquidity: TypedContractMethod<
      [tokenA: AddressLike, tokenB: AddressLike, liquidity: BigNumberish, amountAMin: BigNumberish, amountBMin: BigNumberish, to: AddressLike, deadline: BigNumberish, ],
      [[bigint, bigint] & {amountA: bigint, amountB: bigint }],
      'nonpayable'
    >
    

    
    swapExactTokensForTokens: TypedContractMethod<
      [amountIn: BigNumberish, amountOutMin: BigNumberish, path: AddressLike[], to: AddressLike, deadline: BigNumberish, ],
      [bigint[]],
      'nonpayable'
    >
    

    
    x: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addLiquidity'): TypedContractMethod<
      [tokenA: AddressLike, tokenB: AddressLike, amountADesired: BigNumberish, amountBDesired: BigNumberish, amountAMin: BigNumberish, amountBMin: BigNumberish, to: AddressLike, ],
      [[bigint, bigint, bigint] & {amountA: bigint, amountB: bigint, liquidity: bigint }],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'factory'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getAmountsOut'): TypedContractMethod<
      [amountIn: BigNumberish, path: AddressLike[], ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'removeLiquidity'): TypedContractMethod<
      [tokenA: AddressLike, tokenB: AddressLike, liquidity: BigNumberish, amountAMin: BigNumberish, amountBMin: BigNumberish, to: AddressLike, deadline: BigNumberish, ],
      [[bigint, bigint] & {amountA: bigint, amountB: bigint }],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'swapExactTokensForTokens'): TypedContractMethod<
      [amountIn: BigNumberish, amountOutMin: BigNumberish, path: AddressLike[], to: AddressLike, deadline: BigNumberish, ],
      [bigint[]],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'x'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    getEvent(key: 'Increment'): TypedContractEvent<IncrementEvent.InputTuple, IncrementEvent.OutputTuple, IncrementEvent.OutputObject>;
getEvent(key: 'RemoveEvent'): TypedContractEvent<RemoveEventEvent.InputTuple, RemoveEventEvent.OutputTuple, RemoveEventEvent.OutputObject>;

    filters: {
      
      'Increment(address,address,address,address,uint256,uint256,uint256,uint256,uint256,uint256,uint256)': TypedContractEvent<IncrementEvent.InputTuple, IncrementEvent.OutputTuple, IncrementEvent.OutputObject>;
      Increment: TypedContractEvent<IncrementEvent.InputTuple, IncrementEvent.OutputTuple, IncrementEvent.OutputObject>;
    

      'RemoveEvent(uint256,address,uint256)': TypedContractEvent<RemoveEventEvent.InputTuple, RemoveEventEvent.OutputTuple, RemoveEventEvent.OutputObject>;
      RemoveEvent: TypedContractEvent<RemoveEventEvent.InputTuple, RemoveEventEvent.OutputTuple, RemoveEventEvent.OutputObject>;
    
    };
  }