/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IUniswapV2Callee__factory } from './IUniswapV2Callee__factory.ts';
export { UniswapV2Pair__factory } from './UniswapV2Pair__factory.ts';