/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TokenA } from './TokenA.ts';
export type { TokenB } from './TokenB.ts';
export type { TokenC } from './TokenC.ts';