/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as dexTokenSol from './DexToken.sol/index.ts';
export * as interfacesSol from './Interfaces.sol/index.ts';
export * as uniswapV2PairSol from './UniswapV2Pair.sol/index.ts';
export { UniswapV2Factory__factory } from './UniswapV2Factory__factory.ts';
export { UniswapV2Router__factory } from './UniswapV2Router__factory.ts';