/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IUniswapV2Callee } from './IUniswapV2Callee.ts';
export type { UniswapV2Pair } from './UniswapV2Pair.ts';